FROM node:lts-buster
RUN git clone https://github.com/Um4r719/UMAR-PRIVATE /root/UMAR-PRIVATE
WORKDIR /root/UMAR-PRIVATE
RUN npm install && npm install -g pm2 || yarn install --network-concurrency 1
EXPOSE 9090
CMD ["npm", "start"]
